import Head from 'next/head'
import { Inter } from '@next/font/google'
import LineChart from '../components/LineChart'
import {FaGripLines} from 'react-icons/fa';

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
  const res = await fetch('https://pepper-backend-yash-271120.onrender.com/clicks');
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

export default function Home({data}) {

  const chartData = {
    labels: Object.keys(data.date_to_clicks_map),
    datasets: [{
      label:"Number of clicks",
      data: Object.values(data.date_to_clicks_map),
      borderColor: 'rgb(255, 99, 132)',
      backgroundColor: 'rgba(255, 99, 132, 0.5)'
    }]
  }
  return (
    <div className={`text-black bg-red-50 h-screen`}>
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
        <nav className=" p-5">
            <div className="py-2">
              <ul className="flex items-center cursor-pointer">
                <li>
                  <div className="bg-purple-700 w-11 h-11 p-2 lg:w-14 lg:h-14 lg:p-3 rounded-md">
                    <FaGripLines className=' text-white text-3xl font-bold'/>
                  </div>
                </li>
                <li className="mx-2 font-bold">
                  <h1 className=' text-5xl lg:text-7xl'>Pepper</h1>
                </li>
              </ul>
            </div>   
          </nav>
        </section>
        <section className=' my-5'>
        <div className='text-center'>
            <h1 className=" text-5xl md:text-6xl lg:text-7xl font-semibold">
              Admin Panel
            </h1>
            
          </div>
        </section>
        <section>
          <div className=' lg:flex lg:justify-around h-48'>
            <div className='basis-4/12 lg:flex lg:items-center text-center'>
              <p className='text-xl md:text-2xl lg:text-3xl px-5'>Total Number of clicks: {data.clicks_count}</p>
            </div>
            <LineChart chartData={chartData} className=" lg:basis-8/12"/>
          </div>
        </section>
        
      </main>
    </div>
  )
}
